
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  pathtosolution: 'PizzaBox/'

steps:

# ASP.NET Core
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'JohnP1SonarCloud'
    organization: 'johnmarquezsonar'
    scannerMode: 'MSBuild'
    projectKey: 'sonarp1'
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

- script: 
    dotnet build --configuration $(buildConfiguration)
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test
    --configuration $(buildConfiguration)
    --no-build
    --results-directory $(Build.ArtifactStagingDirectory)/XUnitTestPizza/
    /p:CollectCoverage=true
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet test'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
